#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=12
TOTAL_MINUTES=40

ENV_FILE="${ENV_FILE:-.env}"

banner "Alfred.report go-live"

# ── Staging look ──────────────────────────────────────────────────────────
stage "Staging homepage" 3
say "Check the Worker face — not live alfred.report yet (that is still command-os-review)."
open_url "https://alfred-report.iceberg.workers.dev/"
step "You should see Alfred, report! — tiles ORAL / Missions / Map — Get started → /signup."
step "Footer: Terms left, A product of OpenRoyleAl center, Privacy right."
if confirm "Staging homepage looks right?"; then
  write_env STAGING_HOME_OK yes
else
  warn "Fix staging before cutover. Re-run this script."
  exit 1
fi

stage "KISS paths including /start" 3
say "The sovereign flow is /start — not a second product hostname."
open_url "https://alfred-report.iceberg.workers.dev/start"
step "Open /signup /login /home /start. /wizard must 301 to /start."
step "Invite copy mentions al@alfred.report."
if confirm "Signup, login, home, and /start look right?"; then
  write_env STAGING_KISS_OK yes
else
  exit 1
fi

stage "Legal + crawler files" 2
open_url "https://alfred-report.iceberg.workers.dev/terms"
step "Also open /privacy, /robots.txt, /sitemap.xml, /llms.txt."
step "Sitemap lists /start and /terms, not /wizard. robots.txt Allow: / for * and Googlebot."
if confirm "Legal + robots/sitemap look right?"; then
  write_env STAGING_LEGAL_OK yes
else
  exit 1
fi

# ── Cloudflare Email Routing ──────────────────────────────────────────────
stage "Email Routing — onboard alfred.report" 5
say "Inbound mail only. Cloudflare forwards; it does not send as al@alfred.report."
warn "Enabling Routing adds MX on alfred.report. Skip if this zone already receives mail elsewhere."
open_url "https://dash.cloudflare.com/0870b0bdbc14bcd31f43fe5e82c3ee8e/email/routing"
step "Compute → Email Service → Email Routing → Onboard Domain."
step "Choose zone alfred.report. Review MX, SPF, DKIM Cloudflare will add. Done."
pause "Onboarded (or already onboarded)?"

stage "Destination inbox (where al@ forwards)" 4
open_url "https://dash.cloudflare.com/0870b0bdbc14bcd31f43fe5e82c3ee8e/email/routing/destination-addresses"
step "Destination Addresses → enter Hans's real inbox → submit."
step "Open that inbox, click Verify email address in Cloudflare's message."
ask AL_FORWARD_TO "Verified destination address (e.g. hans@…):"
write_env AL_FORWARD_TO "$AL_FORWARD_TO"
write_env ALFRED_PRODUCT_EMAIL "al@alfred.report"

stage "Routing rule al@alfred.report" 3
open_url "https://dash.cloudflare.com/0870b0bdbc14bcd31f43fe5e82c3ee8e/alfred.report/email/routing/routes"
step "Select domain alfred.report → Routing Rules → Create routing rule."
step "Email pattern local part: al  ·  domain: alfred.report"
step "Action: Send to an email  ·  Destination: the verified inbox from the last step."
pause "Rule saved?"
say "Send a test message to al@alfred.report from another account. It should land in the destination inbox."
pause "Test mail arrived?"

# ── SEO / crawlers ────────────────────────────────────────────────────────
stage "Let crawlers in (Bot Fight Mode)" 3
say "Public pages must 200 for Googlebot and AI crawlers. No special User-Agent."
open_url "https://dash.cloudflare.com/0870b0bdbc14bcd31f43fe5e82c3ee8e/alfred.report/security/settings"
step "Security → Settings (or Bots) for zone alfred.report."
step "Turn Bot Fight Mode OFF, or skip verified bots / known crawlers so Googlebot is not challenged."
pause "Crawlers can fetch / without a custom UA?"

stage "www → apex 301" 4
say "Google already indexed www. We do not serve www as a second site."
say "Do not add a Worker route www.alfred.report/* for the app."
open_url "https://dash.cloudflare.com/0870b0bdbc14bcd31f43fe5e82c3ee8e/alfred.report/rules/redirect-rules"
step "Rules → Redirect Rules → Create rule."
step "If Incoming hostname equals www.alfred.report"
step "Then URL redirect: Dynamic concat(\"https://alfred.report\", http.request.uri.path) — status 301 — preserve query string."
pause "www rule saved?"

stage "iphone.alfred.report leftover" 2
say "iphone.alfred.report was an old Siri-setup hostname. The page is https://alfred.report/iphone — not a subdomain product."
open_url "https://dash.cloudflare.com/0870b0bdbc14bcd31f43fe5e82c3ee8e/alfred.report/rules/redirect-rules"
step "If the DNS record still exists: Redirect Rule hostname equals iphone.alfred.report → static https://alfred.report/iphone 301."
step "If there is no iphone DNS record, skip — nothing to redirect."
pause "iphone host redirected or skipped?"

# ── Cutover (irreversible for vanity) ─────────────────────────────────────
stage "Cutover GO gate" 2
warn "This steals alfred.report/* from Worker command-os-review onto alfred-report."
warn "Do not restore www.* or iphone.* as Worker product routes."
if ! confirm "Hans said GO — attach alfred.report/* to Worker alfred-report now?"; then
  say "Stopped before cutover. Email + www rules can stay. Re-run when you say go."
  finish
  exit 0
fi
write_env CUTOVER_GO yes

stage "Restore apex route + deploy" 5
say "In wrangler.jsonc uncomment ONLY:"
note '  "routes": [ { "pattern": "alfred.report/*", "zone_name": "alfred.report" } ]'
step "Edit wrangler.jsonc on this machine, save, then continue."
pause "Apex route uncommented in wrangler.jsonc?"
if confirm "Run wrangler deploy now? (uses ALFRED_ADMIN_TOKEN from ~/.vault/cloudflare.env — not printed)"; then
  if [[ ! -f "$HOME/.vault/cloudflare.env" ]]; then
    warn "missing ~/.vault/cloudflare.env — deploy by hand"
  else
    # shellcheck disable=SC1091
    set -a
    # shellcheck disable=SC1090
    source "$HOME/.vault/cloudflare.env"
    [[ -f "$HOME/.vault/alfred-ops.env" ]] && source "$HOME/.vault/alfred-ops.env"
    set +a
    CLOUDFLARE_API_TOKEN="$ALFRED_ADMIN_TOKEN" npx wrangler deploy
  fi
else
  note "Deploy later: CLOUDFLARE_API_TOKEN=\"\$ALFRED_ADMIN_TOKEN\" npx wrangler deploy"
fi

stage "Live vanity check" 4
open_url "https://alfred.report/"
step "Same homepage as staging. /start not /wizard. Footer OpenRoyleAl. www.alfred.report 301s to apex."
step "curl -sSIL https://www.alfred.report/ should show Location: https://alfred.report/"
if confirm "Live alfred.report matches staging and www 301s?"; then
  write_env LIVE_CUTOVER_OK yes
fi

finish
